/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
Author: thegraphicsgeek (https://sketchfab.com/thegraphicsgeek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gameboy-advance-sp-18c9688eaa8f4903a940c105242df15f
Title: Gameboy Advance SP
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -2.175, -4.528]} rotation={[1.309, 0, 0]}>
          <mesh geometry={nodes.TopScreen_Frame_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
          <mesh geometry={nodes.Top_LargeHinge_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
          <mesh geometry={nodes.Top_SmallHinge_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
          <mesh geometry={nodes.ScreenGuard_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
          <mesh geometry={nodes.LogoSticker_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
          <mesh geometry={nodes.ScreenGlass_geo_ScreenGlass_MAT_0.geometry} material={materials.ScreenGlass_MAT} />
          <mesh geometry={nodes.ScreenCover_geo_ScreenGlass_MAT_0.geometry} material={materials.ScreenGlass_MAT} />
          <mesh geometry={nodes.Sceren_geo_Screen_MAT_0.geometry} material={materials.Screen_MAT} />
        </group>
        <mesh geometry={nodes.Base_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.Btm_Label_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.Power_LED01_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.Power_LED02_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.Battery_Lid_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.RKesnsignton_Lock_End_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.LKesnsignton_Lock_End_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.BatterLid_Screw_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.PowerBtn_Base_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.PowerBtn_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.VolumeBtn_Base_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.VolumeBtn_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.HingeCorner_RMid_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.HingeCorner_LMid_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.ChargingPort_Frame_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.ChargingPort_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.ChargingPort_Mid_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.LinkPort_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.LinkPort_Mid_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.LinkPort_Frame_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.Select_Btn_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.Start_Btn_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.B_Btn_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.A_Btn_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.Brightness_Btn_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.DPad_geo_Gameboy_1002_MAT_0.geometry} material={materials.Gameboy_1002_MAT} />
        <mesh geometry={nodes.R_ShoulderBtn_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.R_ShoulderButn_Inside_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.L_ShoulderButn_Inside_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.L_ShoulderBtn_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.CartridgeSlot_Teeth_geo_Gameboy_1001_MAT_0.geometry} material={materials.Gameboy_1001_MAT} />
        <mesh geometry={nodes.OffText_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.OnText_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.OnDot_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.OffDot_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.VolText_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.VolDot_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
        <mesh geometry={nodes.VolBar_geo_Gameboy_1003_MAT_0.geometry} material={materials.Gameboy_1003_MAT} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
